// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/orderbook_socket/v1/orderbook.proto

package orderbook_socket_v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Orderbook struct {
	Pair                             string           `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Bids                             []*OrderbookItem `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks                             []*OrderbookItem `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	TwentyFourHourVolume             float64          `protobuf:"fixed64,4,opt,name=twenty_four_hour_volume,json=twentyFourHourVolume,proto3" json:"twenty_four_hour_volume,omitempty"`
	TwentyFourHourLow                float64          `protobuf:"fixed64,5,opt,name=twenty_four_hour_low,json=twentyFourHourLow,proto3" json:"twenty_four_hour_low,omitempty"`
	TwentyFourHourHigh               float64          `protobuf:"fixed64,6,opt,name=twenty_four_hour_high,json=twentyFourHourHigh,proto3" json:"twenty_four_hour_high,omitempty"`
	TwentyFourHourChange             float64          `protobuf:"fixed64,7,opt,name=twenty_four_hour_change,json=twentyFourHourChange,proto3" json:"twenty_four_hour_change,omitempty"`
	LastTradePrice                   float64          `protobuf:"fixed64,8,opt,name=last_trade_price,json=lastTradePrice,proto3" json:"last_trade_price,omitempty"`
	Spread                           float64          `protobuf:"fixed64,9,opt,name=spread,proto3" json:"spread,omitempty"`
	TwentyFourHourPercentChange      float64          `protobuf:"fixed64,10,opt,name=twenty_four_hour_percent_change,json=twentyFourHourPercentChange,proto3" json:"twenty_four_hour_percent_change,omitempty"`
	TwentyFourHourPricePercentChange float64          `protobuf:"fixed64,11,opt,name=twenty_four_hour_price_percent_change,json=twentyFourHourPricePercentChange,proto3" json:"twenty_four_hour_price_percent_change,omitempty"`
	XXX_NoUnkeyedLiteral             struct{}         `json:"-"`
	XXX_unrecognized                 []byte           `json:"-"`
	XXX_sizecache                    int32            `json:"-"`
}

func (m *Orderbook) Reset()         { *m = Orderbook{} }
func (m *Orderbook) String() string { return proto.CompactTextString(m) }
func (*Orderbook) ProtoMessage()    {}
func (*Orderbook) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab2a4dda4f982247, []int{0}
}

func (m *Orderbook) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Orderbook.Unmarshal(m, b)
}
func (m *Orderbook) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Orderbook.Marshal(b, m, deterministic)
}
func (m *Orderbook) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Orderbook.Merge(m, src)
}
func (m *Orderbook) XXX_Size() int {
	return xxx_messageInfo_Orderbook.Size(m)
}
func (m *Orderbook) XXX_DiscardUnknown() {
	xxx_messageInfo_Orderbook.DiscardUnknown(m)
}

var xxx_messageInfo_Orderbook proto.InternalMessageInfo

func (m *Orderbook) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *Orderbook) GetBids() []*OrderbookItem {
	if m != nil {
		return m.Bids
	}
	return nil
}

func (m *Orderbook) GetAsks() []*OrderbookItem {
	if m != nil {
		return m.Asks
	}
	return nil
}

func (m *Orderbook) GetTwentyFourHourVolume() float64 {
	if m != nil {
		return m.TwentyFourHourVolume
	}
	return 0
}

func (m *Orderbook) GetTwentyFourHourLow() float64 {
	if m != nil {
		return m.TwentyFourHourLow
	}
	return 0
}

func (m *Orderbook) GetTwentyFourHourHigh() float64 {
	if m != nil {
		return m.TwentyFourHourHigh
	}
	return 0
}

func (m *Orderbook) GetTwentyFourHourChange() float64 {
	if m != nil {
		return m.TwentyFourHourChange
	}
	return 0
}

func (m *Orderbook) GetLastTradePrice() float64 {
	if m != nil {
		return m.LastTradePrice
	}
	return 0
}

func (m *Orderbook) GetSpread() float64 {
	if m != nil {
		return m.Spread
	}
	return 0
}

func (m *Orderbook) GetTwentyFourHourPercentChange() float64 {
	if m != nil {
		return m.TwentyFourHourPercentChange
	}
	return 0
}

func (m *Orderbook) GetTwentyFourHourPricePercentChange() float64 {
	if m != nil {
		return m.TwentyFourHourPricePercentChange
	}
	return 0
}

type OrderbookItem struct {
	Price                float64  `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Quantity             float64  `protobuf:"fixed64,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderbookItem) Reset()         { *m = OrderbookItem{} }
func (m *OrderbookItem) String() string { return proto.CompactTextString(m) }
func (*OrderbookItem) ProtoMessage()    {}
func (*OrderbookItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ab2a4dda4f982247, []int{1}
}

func (m *OrderbookItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderbookItem.Unmarshal(m, b)
}
func (m *OrderbookItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderbookItem.Marshal(b, m, deterministic)
}
func (m *OrderbookItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderbookItem.Merge(m, src)
}
func (m *OrderbookItem) XXX_Size() int {
	return xxx_messageInfo_OrderbookItem.Size(m)
}
func (m *OrderbookItem) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderbookItem.DiscardUnknown(m)
}

var xxx_messageInfo_OrderbookItem proto.InternalMessageInfo

func (m *OrderbookItem) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OrderbookItem) GetQuantity() float64 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterType((*Orderbook)(nil), "orderbook_socket.v1.Orderbook")
	proto.RegisterType((*OrderbookItem)(nil), "orderbook_socket.v1.OrderbookItem")
}

func init() {
	proto.RegisterFile("proto/orderbook_socket/v1/orderbook.proto", fileDescriptor_ab2a4dda4f982247)
}

var fileDescriptor_ab2a4dda4f982247 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xd1, 0x4b, 0xc2, 0x50,
	0x14, 0xc6, 0x99, 0x4e, 0xd3, 0x23, 0x45, 0x9d, 0xac, 0x2e, 0xf5, 0xd0, 0x10, 0x82, 0xf5, 0x32,
	0xb1, 0xa8, 0xf7, 0x28, 0xc2, 0x20, 0x50, 0x24, 0x7a, 0x1d, 0x73, 0xbb, 0xb9, 0xa1, 0xee, 0xae,
	0xbb, 0x3b, 0xc5, 0x7f, 0xad, 0xbf, 0x2e, 0xee, 0x99, 0x1a, 0x73, 0x3e, 0xf4, 0x32, 0x76, 0xce,
	0xf7, 0xfd, 0xbe, 0xfb, 0x8d, 0x5d, 0xb8, 0x4d, 0xa4, 0x50, 0xa2, 0x2b, 0x64, 0xc0, 0xe5, 0x58,
	0x88, 0xa9, 0x9b, 0x0a, 0x7f, 0xca, 0x55, 0x77, 0xd1, 0xfb, 0xdb, 0x39, 0xe4, 0xc1, 0xd3, 0x5d,
	0x93, 0xb3, 0xe8, 0x75, 0x7e, 0x4c, 0x68, 0x0e, 0x36, 0x7b, 0x44, 0x30, 0x13, 0x2f, 0x92, 0xcc,
	0xb0, 0x0c, 0xbb, 0x39, 0xa2, 0x77, 0x7c, 0x04, 0x73, 0x1c, 0x05, 0x29, 0xab, 0x58, 0x55, 0xbb,
	0x75, 0xd7, 0x71, 0xf6, 0xa4, 0x38, 0xdb, 0x84, 0x37, 0xc5, 0xe7, 0x23, 0xf2, 0x6b, 0xce, 0x4b,
	0xa7, 0x29, 0xab, 0xfe, 0x9f, 0xd3, 0x7e, 0x7c, 0x80, 0x0b, 0xb5, 0xe4, 0xb1, 0x5a, 0xb9, 0x5f,
	0x22, 0x93, 0x6e, 0xa8, 0x1f, 0x0b, 0x31, 0xcb, 0xe6, 0x9c, 0x99, 0x96, 0x61, 0x1b, 0xa3, 0x76,
	0x2e, 0xbf, 0x8a, 0x4c, 0xf6, 0x45, 0x26, 0x3f, 0x49, 0xc3, 0x2e, 0xb4, 0x4b, 0xd8, 0x4c, 0x2c,
	0x59, 0x8d, 0x98, 0x93, 0x22, 0xf3, 0x2e, 0x96, 0xd8, 0x83, 0xb3, 0x12, 0x10, 0x46, 0x93, 0x90,
	0xd5, 0x89, 0xc0, 0x22, 0xd1, 0x8f, 0x26, 0xe1, 0xde, 0x6a, 0x7e, 0xe8, 0xc5, 0x13, 0xce, 0x0e,
	0xf6, 0x55, 0x7b, 0x26, 0x0d, 0x6d, 0x38, 0x9e, 0x79, 0xa9, 0x72, 0x95, 0xf4, 0x02, 0xee, 0x26,
	0x32, 0xf2, 0x39, 0x6b, 0x90, 0xff, 0x48, 0xef, 0x3f, 0xf4, 0x7a, 0xa8, 0xb7, 0x78, 0x0e, 0xf5,
	0x34, 0x91, 0xdc, 0x0b, 0x58, 0x93, 0xf4, 0xf5, 0x84, 0x2f, 0x70, 0x5d, 0x3a, 0x38, 0xe1, 0xd2,
	0xe7, 0xb1, 0xda, 0x14, 0x00, 0x02, 0xae, 0x8a, 0x05, 0x86, 0xb9, 0x67, 0xdd, 0x63, 0x00, 0x37,
	0xe5, 0x14, 0x7d, 0xee, 0x6e, 0x56, 0x8b, 0xb2, 0xac, 0x9d, 0x2c, 0xed, 0x2c, 0x04, 0x76, 0x9e,
	0xe0, 0xb0, 0xf0, 0x07, 0xb1, 0x0d, 0xb5, 0xfc, 0xf3, 0x0c, 0x4a, 0xc8, 0x07, 0xbc, 0x84, 0xc6,
	0x77, 0xe6, 0xc5, 0x2a, 0x52, 0x2b, 0x56, 0x21, 0x61, 0x3b, 0x8f, 0xeb, 0x74, 0x37, 0xef, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xd5, 0xea, 0x15, 0xc8, 0x02, 0x00, 0x00,
}
